apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../imagestreams/cuda-jupyter-tensorflow
  - ../../imagestreams/jupyter-cpp-cling
  - ../../imagestreams/jupyter-rust
  - ../../imagestreams/vscode-cpp-cling
  - ../../imagestreams/vscode-java
